services:
  app:
    build: .
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
    depends_on:
      - tests

  tests:
    build: .
    volumes:
      - .:/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=test
    command: >
      sh -c "mkdir -p logs && npm test | tee logs/test_results.log;
             if [ $? -ne 0 ]; then echo '❌ TESTS ÉCHOUÉS - Consultez logs/test_results.log' && exit 1; fi"
