name: CI Pipeline for Node.js

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test sur plusieurs versions de Node.js
        node-version: [16, 18, 20]
    steps:
      # Récupère le code du repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # Active le cache pour npm
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # Vérifie le code
      - name: Run Linter (ESLint)
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      # Vérifie le formatage
      - name: Run Prettier Check
        run: npx prettier --check .
      # Exécute les tests
      - name: Run Tests
        run: npm test

  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Commit Messages (Commitlint)
        uses: wagoid/commitlint-github-action@v5
