name: CI Pipeline for Node.js

on: # all but main branch
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test more than one node version
        node-version: [18, 20]
    steps:
      # get code from repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # caching install - gain time
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      # lint the code
      - name: Run Linter (ESLint)
        run: npx eslint .
      # check writing issues 
      - name: Run Prettier Check
        run: npx prettier --check .
      # launch tests
      - name: Run Tests
        run: npm test

  check-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # "feat: ... " => can add theme : "feat(auth): ..."
        # "fix: ... "
        # "docs: ... "
      - name: Check Commit Messages (Commitlint)
        uses: wagoid/commitlint-github-action@v5
