name: CI pour Node.js

name: CI testing on Node Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # get code from repo ????????

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' // keep it up to date

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test 

      

  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      # Steps to checkout code, setup Node, install dependencies, and run linter

